api = "0.4"

[buildpack]
id = "dzuelke/php-engine"
version = "0.1.0"
name = "Very basic buildpack that installs a fixed version of the PHP runtime"

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
php_url = "https://lang-php.s3.amazonaws.com/dist-heroku-18-stable/php-8.0.10.tar.gz"
