api = "0.4"

[buildpack]
id = "dzuelke/php-engine-cnb"
version = "0.0.0"
name = "Very basic buildpack that installs a fixed version of the PHP runtime"

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
